apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-app
spec:
  selector:
    matchLabels:
      app: product-service-app
  template:
    metadata:
      labels:
        app: product-service-app
    spec:
      containers:
      - name: product-service-app
        image: IMAGE_URL/productservice
        ports:
        - containerPort: 8080
        env:
          #- name: EUREKA_SERVER_ADDRESS
            #valueFrom:
              #configMapKeyRef:
                #key: eureka_service_address
                #name: eureka-cm
          - name: CONFIG_SERVER_URL
            valueFrom:
              configMapKeyRef:
                key: config_url
                name: config-cm
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                key: hostname
                name: postgresql-cm
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                key: postgres_user
                name: postgresql-cm
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: postgres_password
                name: postgresql-cm

---
apiVersion: v1
kind: Service
metadata:
  name: product-service-svc
spec:
  selector:
    app: product-service-app
  ports:
  - port: 80
    targetPort: 8080
