server:
  port: 9090

spring:
  redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
  application:
    name: API-GATEWAY
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
  cloud:
    gateway:
      routes:
        - id: ORDER-SERVICE
          uri: http://order-service-svc
          predicates:
            - Path=/order/**
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: ORDER-SERVICE
                fallbackuri: forward:/orderServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        - id: PAYMENT-SERVICE
          uri: http://payment-service-svc
          predicates:
            - Path=/payment/**
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: PAYMENT-SERVICE
                fallbackuri: forward:/paymentServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1

        - id: PRODUCT-SERVICE
          uri: http://product-service-svc
          predicates:
            - Path=/product/**
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: PRODUCT-SERVICE
                fallbackuri: forward:/productServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1 #permite una solicitud por segundo
                redis-rate-limiter.burstCapacity: 1 #rafagas permitidads para las peticiones

        - id: IDENTITY-SERVICE
          uri: http://identity-service-svc
          predicates:
            - Path=/auth/**
          filters:
            #- AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: IDENTITY-SERVICE
                fallbackuri: forward:/authServiceFallback
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1 #permite una solicitud por segundo
                redis-rate-limiter.burstCapacity: 1 #rafagas permitidads para las peticiones
